test: fix run_tests() in RUNTESTS.py
The 'c' context has to be initilized before the 'for' loop,
because cf.get_contexts() can return no value ([])
and in case of the 'futils.Fail' exception
self._test_failed(tc, c, f) will be called
with uninitilized value of the 'c' context:

[...]
    raise futils.Fail('Error: ...')
futils.Fail: Error: ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./RUNTESTS.py", line 172, in <module>
    main()
  File "./RUNTESTS.py", line 168, in main
    sys.exit(runner.run_tests())
  File "./RUNTESTS.py", line 110, in run_tests
    self._test_failed(tc, c, f)
UnboundLocalError: local variable 'c' referenced before assignment