test: don't use a FILE pointer after fclose
GCC 12 considers this wrong:
ut_file.c:92:17: error: pointer ‘stream’ may be used after ‘fclose’
    [-Werror=use-after-free]
In our case the pointer doesn't actually get dereferenced -- but then,
knowing its no longer valid value doesn't help in debugging, thus
there's no point in arguing with the compiler.