XXX pool.c hack include pmdk queue.h first to avoid conflict with FreeBSD
https://github.com/pmem/issues/issues/990

pmdk includes a derived copy of FreeBSD's /usr/include/sys/queue.h, and both end up being included (FreeBSD's via some other system header, presumably) when compiling pool.c.

Then because of the

include guard in pmdk's queue.h pmdk's copy does not get used.

Full log:

cc -MD -c -o ../nondebug/libpmempool/pool.o -Wno-unused-value -DENODATA=ENOATTR -std=gnu99 -fno-common -pthread -DSRCVERSION=\"1.5+git131.g39698630e\"   -DUSE_LIBDL -DUSE_RPMEM -I../../src/../src/libpmemlog -I../../src/../src/libpmemblk -I../../src/../src/libpmemobj -I../../src/../src/rpmem_common -I../../src/../src/librpmem -I../include -I../common/ -I../../src/../src/freebsd/include -I/usr/local/include -fPIC  pool.c
In file included from pool.c:70:
../common/mmap.h:113:2: error: type name requires a specifier or qualifier
        SORTEDQ_ENTRY(map_tracker) entry;
        ^
../common/mmap.h:113:16: error: a parameter list without types is only allowed
      in a function definition
        SORTEDQ_ENTRY(map_tracker) entry;
                      ^
../common/mmap.h:113:28: error: expected ';' at end of declaration list
        SORTEDQ_ENTRY(map_tracker) entry;
                                  ^
                                  ;
3 errors generated.