rpmem: switch to using an open coded basename
On FreeBSD, clang fails with the error:

> rpmemd_log.c:199:26: error: passing 'const char *' to parameter of
>  type 'char *' discards qualifiers
>   [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
>     "[%s:%d] ", basename(fname), lineno);
>                          ^~~~~

Which is right, in fact posix states, "The basename() function may
modify the string pointed to by path..." And FreeBSD's basename(3)
does do such in-place modification.

Replace the call to basename with our own function
`rpmemd_log_basename`. It doesn't have handling for trailing
slashes like POSIX basename, but we don't need those anyway as the
function is only ever applied to filenames. This lets us avoid the
need for making any string copies on systems where basename may do
in-place modifications.