pool: Match function prototypes of enum_to_str_fn function pointer
This is flagged by clang 16+

e.g.
common.c:844: error: cast from 'const char *(*)(enum chunk_type)'
to 'enum_to_str_fn' (aka 'const char *(*)(int)')
converts to incompatible function type
[-Werror,-Wcast-function-type-strict]

Signed-off-by: Khem Raj <raj.khem@gmail.com>