win: avoid exceeding max array size limit
Code refactoring to avoid max array size limit error, when compiling
with VS2015.
To avoid compilation error C2233
"'zones' : arrays of objects containing zero-size arrays are illegal",
each object in an array must contain at least one element.