test: fix convert_to_bytes to actually return a number
Fixes require_free_space failure:

obj_root/TEST0: SETUP (check\pmem\debug)
Cannot convert value "19327352832966367641.6" to type "System.Int64".
Error: "Input string was not in a correct format."
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger
    + PSComputerName        : localhost

obj_root/TEST0: PASS			[00.957 s]